CREATE TABLE AUTOR(
  Codigo_Autor INTEGER NOT NULL,
  Nome_Autor VARCHAR(60) NULL
);

ALTER TABLE AUTOR
  ADD (PRIMARY KEY (Codigo_Autor));

CREATE TABLE CD (
  Codigo_CD INTEGER NOT NULL,
  Codigo_Gravadora INTEGER NULL,
  Nome_CD VARCHAR(60) NULL,
  Preco_Venda DECIMAL(16,2) NULL,
  Data_Lancamento DATE NULL,
  CD_Indicado INTEGER NULL
);

ALTER TABLE CD 
  ADD (PRIMARY KEY (Codigo_CD));

CREATE TABLE GRAVADORA(
  Codigo_Gravadora INTEGER NOT NULL,
  Nome_Gravadora VARCHAR(60) NULL,
  Endereco VARCHAR(60) NULL,
  Telefone VARCHAR(20) NULL,
  Contato VARCHAR(20) NULL,
  URL VARCHAR(80) NULL
);

ALTER TABLE GRAVADORA
  ADD (PRIMARY KEY (Codigo_Gravadora));

CREATE TABLE FAIXA (
  Codigo_Musica INTEGER NOT NULL,
  Codigo_CD INTEGER NOT NULL,
  Numero_Faixa INTEGER NULL
);

ALTER TABLE ITEM_CD 
  ADD (PRIMARY KEY(Codigo_Musica, Codigo_CD));

CREATE TABLE MUSICA (
  Codigo_Musica INTEGER NOT NULL,
  Nome_Musica VARCHAR(60) NULL,
  Duracao(6,2) NULL
);

ALTER TABLE MUSICA
  ADD (PRIMARY KEY (Codigo_Musica));

CREATE TABLE MUSICA_AUTOR(
  Codigo_Musica INTEGER NOT NULL,
  Codigo_Autor INTEGER NOT NULL
);

ALTER TABLE MUSICA_AUTOR
  ADD(PRIMARY KEY (Codigo_Musica, Codigo_Autor));

CREATE TABLE CD_CATEGORIA(
  Codigo_Categoria INTEGER NOT NULL,
  Menor_Preco DECIMAL(14,2) NOT NULL,
  Maior_Preco DECIMAL(14,2) NOT NULL
);

ALTER TABLE CD 
  ADD (FOREIGN KEY (Codigo_Gravadora)
  REFERENCES GRAVADORA
);
ALTER TABLE CD 
  ADD (CONSTRAINT CD_CD
  FOREIGN KEY (CD_Indicado)
  REFERENCES CD
);

ALTER TABLE FAIXA
  ADD (FOREIGN KEY (Codigo_CD)
  REFERENCES CD
);

ALTER TABLE FAIXA
  ADD (FORENGIN KEY (Codigo_CD)
  REFERENCES CD
);

ALTER TABLE MUSICA_AUTOR
  ADD (FOREIGN KEY (Codigo_Autor)
  REFERENCES AUTOR
);

ALTER TABLE MUSICA_AUTOR
  ADD (FORENGIN KEY (Codigo_Musica)
  REFERENCES MUSICA
);
  
